### PR TITLE
BHBC-1571

### PR DESCRIPTION
**Pull request by cgarrettjones**
BHBC-1583

# Overview

- [BHBC-1571](https://quartech.atlassian.net/browse/BHBC-1571)
- [BHBC-1583](https://quartech.atlassian.net/browse/BHBC-1583)

## This PR contains the following changes

- support multiple contacts and contact types
- support project species

## This PR contains the following types of changes

- [ ] New feature (change which adds functionality)
- [ ] Enhancement (improvements to existing functionality)
- [ ] Bug fix (change which fixes an issue)
- [ ] Misc cleanup / Refactoring / Documentation
- [ ] Version change

## Checklist

A list of items that are good to consider when making any changes.

_Note: this list is not exhaustive, and not all items are always applicable._

### General

- [ ] I have performed a self-review of my own code

### Code

- [ ] New files/classes/functions have appropriately descriptive names and comment blocks to describe their use/behaviour
- [ ] I have avoided duplicating code when possible, moving re-usable pieces into functions
- [ ] I have avoided hard-coding values where possible and moved any re-usable constants to a constants file
- [ ] My code is as flat as possible (avoids deeply nested if/else blocks, promise chains, etc)
- [ ] My code changes account for null/undefined values and handle errors appropriately
- [ ] My code uses types/interfaces to help describe values/parameters/etc, help ensure type safety, and improve readability

### Style

- [ ] My code follows the established style conventions
- [ ] My code uses native material-ui components/icons/conventions when possible

### Documentation

- [ ] I have commented my code sufficiently, such that an unfamiliar developer could understand my code
- [ ] I have added/updated README's and related documentation, as needed

### Tests

- [ ] I have added/updated unit tests for any code I've added/updated
- [ ] I have added/updated the Postman requests/tests to account for any API endpoints I've added/updated

### Linting/Formatting

- [ ] I have run the linter and fixed any issues, as needed  
       _See the `lint` commands in package.json_
- [ ] I have run the formatter and fixed any issues, as needed  
       _See the `format` commands in package.json_

### SonarCloud

- [ ] I have addressed all SonarCloud Bugs, Vulnerabilities, Security Hotspots, and Code Smells

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Screenshots

Please add any relevant UI screenshots, if applicable.

### CODE REVIEW

**Comment by anissa-agahchen** [comment]
@cgarrettjones, I'm getting this error when running your PR locally on retrieving projects here : http://localhost:6100/api/projects

Screen Shot 2022-02-08 at 8 54 13 AM

**Comment by NickPhura** [comment]
> @cgarrettjones, I'm getting this error when running your PR locally on retrieving projects here : http://localhost:6100/api/projects
> 
> Screen Shot 2022-02-08 at 8 54 13 AM

Looks like some old sql that is referencing coordinator information from the project table, which doesnt exist anymore. Most of the coordinator stuff will need updating to work with the new models.  In past we just committed those api/app changes into this PR. @shreypdev can probably take a look at this, as its related to his ticket for the contacts and will impact the backend changes he'll need.

**Review by shreypdev — COMMENTED** [review]
I reviewed the changes and it looks good to me. Also testing on [BHBC-1570](https://github.com/bcgov/restoration-tracker/tree/BHBC-1570-add-multiple-contacts-for-restoration-projects) by fixing the error that was popping. I think @cgarrettjones we can close this branch and PR.

**Comment by cgarrettjones** [comment]
> I reviewed the changes and it looks good to me. Also testing on [BHBC-1570](https://github.com/bcgov/restoration-tracker/tree/BHBC-1570-add-multiple-contacts-for-restoration-projects) by fixing the error that was popping. I think @cgarrettjones we can close this branch and PR.

**Comment by shreypdev** [comment]
Merged new changes from this PR into https://github.com/bcgov/restoration-tracker/pull/18. So this PR and Branch can be now closed.

**Pull request closed without merging**
